language: go
go: '1.10'
install:
  - make setup-deps
script: make build
deploy:
  - provider: script
    skip_cleanup: true
    script: curl -sL https://git.io/goreleaser | bash -s -- --rm-dist
    on:
      tags: true
notifications:
  email: false
